### ISSUE TITLE
Suggestion - MySQLi support

### ISSUE THREAD

**Issue by master3395** [lewisakura/webhook-proxy#6]
Hello,

I would love to be able to use MySQLi to log all the blocked requests, errors, etc, and all of the database information.
Instead of spamming the other logs.

I just had to delete a whole log file on errors, because all it logs is full of attempts on blocked.
There was over 100000KB of such.
And it keeps growing each second/min.

`[30;43m 2023-07-28T21:40:36.567Z [0m [30;43m ! [0m Censored. (belonging to Censored.) attempted to request whilst blocked for [Automated] Ratelimited >50 times within a minute.`

Here is the last 3 minutes.
Storing it in the MySQLi would make the log size smaller, and perhaps have an option to ditch old log files after 24 hours or so?
![image](https://github.com/lewisakura/webhook-proxy/assets/4199669/b1489d94-7e00-4011-8b94-e5ee7be2f62c)
![image](https://github.com/lewisakura/webhook-proxy/assets/4199669/d5657b05-65d8-473a-bc40-245788e3112f)
![image](https://github.com/lewisakura/webhook-proxy/assets/4199669/a64c31b8-ef3e-44bb-8e5f-f04f7dd13300)

**Comment by lewisakura** [comment]
There is already a [logrotate module for pm2](https://www.npmjs.com/package/pm2-logrotate) and doing it in the application is out of scope.

**Comment by master3395** [comment]
I still find it easier to edit the webhook ban log, if it was in a MySQLi database instead of in a PDO.
Because I do not know if there is any command to remove the banned webhooks from the PDO without stopping the webhook and then restarting it.
