### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by master3395** [lewisakura/webhook-proxy#8]
Hello, i had a customer that sent this to me.
Perhaps that is something to consider adding?

> After a while of experimenting, I notice there a down side of using this proxy is that you cannot send multipart/form-data. Here an example:
> The code below is use for uploading a file to discord via webhook and JavaScript, it work perfectly fine when I use normal webhook url but return 400 - Bad Request when use your proxy url, you can test it by yourself by replace the url in the first parameter of "fetch" function with your own webhook url then run it in a JavaScript environment.
> 

```
fetch("https://discord.com/api/webhooks/ID/TOKEN?wait=true", {
"headers": {"Content-Type": "multipart/form-data; boundary=----WebKitFormBoundarycoFNJ32D5HqiucOT"},
"body": "------WebKitFormBoundarycoFNJ32D5HqiucOT\r\nContent-Disposition: form-data; name=\"file[0]\"; filename=\"TestingFile.txt\"\r\nContent-Type: text/plain\r\n\r\nTHIS_IS_THE_CONTENT_OF_THE_FILE\r\n------WebKitFormBoundarycoFNJ32D5HqiucOT--\r\n",
"method": "POST"
});
```

**Comment by lewisakura** [comment]
there isn't really a real reason to use files though when this proxy is designed for roblox games which don't really support them, so what's the use case here?

**Comment by master3395** [comment]
This is the response i got from the user.
So the user means he wants to use the attachment system, while your system does not have access to it, I believe.

> I apologize if my previous message was unclear.
> 
> I understand that Roblox does not have a file system, but this doesn't mean it cannot function without one. My use case for this is to send report data to Discord. Sometimes, the report data might be quite large, around 1-2MB, and we cannot fit such data into a single Discord message without using an attachment (file).
> 
> Here a piece of code so it easier to understand:
> 
> const webhookUrl = "https://discord.com/api/webhooks/ID/TOKEN";
> const fileName = "File.txt";
> const fileContentType = "text/plain";
> const fileContent = "As you can see from this code, we don't require Roblox to have a file system for this to function. Instead, we simply need to place the file content within this string and send it to a Discord webhook. Discord will then generate an attachment containing the file content we have specified here.";

```
fetch(webhookUrl, {
 "headers": {"Content-Type": "multipart/form-data; boundary=----WebKitFormBoundarycoFNJ32D5HqiucOT"},
 "body": `------WebKitFormBoundarycoFNJ32D5HqiucOT\r\nContent-Disposition: form-data; name="file[0]"; filename="${fileName}"\r\nContent-Type: ${fileContentType}\r\n\r\n${fileContent}\r\n------WebKitFormBoundarycoFNJ32D5HqiucOT--\r\n`,
 "method": "POST"
});
```

**Comment by lewisakura** [comment]
1-2mb of text..? that's huge for a webhook message and sounds like it should really be uploaded somewhere else

i really don't like the idea of allowing games to submit arbitrary file data down a proxy when said files could be uploaded somewhere else first and linked to by a discord message - it seems very easily abusable 

also, as shown by their own example, it's extremely inconvenient to do this and requires setting up the whole multipart form data thing yourself
